### ISSUE TITLE
Persistent styling

### ISSUE THREAD

**Issue by JR-prog** [Ariiiane/InGame-Emporium-soen341project2022#13]
As a user, I want the browsing experience to be seamless, because some websites nowadays have incoherent navigation and styling, which is confusing when I am browsing (and might deter me from staying on the website for very long).

For the entire website to have cohesive aesthetics and functionality we must do the following:
- [x] #10 
- [x] #11 
- [x] #12 

Yay! Now we can reuse all this on nearly every page.

**Comment by MariaR001** [comment]
General styling info is available on wiki. To be reviewed.
