### ISSUE TITLE
Remember me function bugged

### ISSUE THREAD

**Issue by JR-prog** [Ariiiane/InGame-Emporium-soen341project2022#47]
I cannot log in with the "remember me" button checked. (If you want we can be cheeky and just remove the functionality altogether :^), or fix it)

![image](https://user-images.githubusercontent.com/52092026/159177895-830d27f0-1092-4f88-a1e4-f104f7f92b6d.png)

Or maybe were there migrations to make to the DB?

**Comment by chloehylaw** [comment]
Bug fix remember me button function 

Story point: 1
